imports:
  - { resource: vendor/henrivantsant/henri/src/Framework/services.yaml }
  - { resource: vendor/henrivantsant/henri/src/Application/services.yaml}

parameters:
# ...

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true