imports:
  - { resource: vendor/henrivantsant/henri/Framework/services.yaml }
  - { resource: vendor/henrivantsant/henri/Application/services.yaml}

parameters:
# ...

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true