parameters:
# ...

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Doctrine\Common\Annotations\AnnotationReader: ~

  Henri\Framework\:
    resource: 'vendor/henrivantsant/henri/Framework/*'
    exclude: ['Monolog/Logger']