parameters:
# ...

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Henri\Framework\:
    resource: 'vendor/henrivantsant/henri/Framework/*'
    exclude: ['Monolog/Logger']