parameters:
# ...

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Henri\Application\:
    resource: 'src/henri/Application/*'
    exclude: 'src/henri/Application/Bootstrap/*'